---
driver:
  name: dokken
  privileged: true # because Docker and SystemD/Upstart
  chef_version: <%= ENV['CHEF_VERSION'] || 'current' %>

transport:
  name: dokken

provisioner:
  name: dokken
  deprecations_as_errors: true

verifier:
  name: inspec
  chef_license: accept

platforms:
  - name: ubuntu-18.04
    driver:
      image: dokken/ubuntu-18.04
      pid_one_command: /bin/systemd
  - name: debian-9
    driver:
      image: dokken/debian-9
      pid_one_command: /bin/systemd

suites:
  - name: default
    run_list:
      - recipe[ipfs::default]
    attributes:
