---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-18.04
  - name: debian-9

verifier:
  chef_license: accept

suites:
  - name: default
    run_list:
      - recipe[ipfs::default]
    attributes:
