---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-18.04
  - name: debian-9

suites:
  - name: default
    run_list:
      - recipe[ipfs::default]
    attributes:
  - name: cluster
    run_list:
      - recipe[ipfs::cluster]
      - recipe[ipfs::cluster_service]
    attributes:
